[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:socat]
command=/usr/local/bin/start_socat.sh
autostart=true
autorestart=true
priority=1
stdout_logfile=/var/log/socat_stdout.log
stderr_logfile=/var/log/socat_stderr.log

[program:tomcat]
command=/opt/tomcat/bin/catalina.sh run
autostart=true
autorestart=true
priority=10
startsecs=10
startretries=5
environment=JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64",CATALINA_HOME="/opt/tomcat"
stdout_logfile=/var/log/tomcat_stdout.log
stderr_logfile=/var/log/tomcat_stderr.log

